version: '3'
services:
  snaretanner:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DNS_SERVER=8.8.8.8
    ports:
      - "80:80"
      - "7777:7777"
      - "8088:8088"
      - "8090:8090"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "opt/snare/pages/sakec.ac.in:opt/snare/pages/sakec.ac.in:rw"
    entrypoint: ["./run.sh"]
    stdin_open: true
    tty: true
